### PR TITLE
Added images column for activity table

### PR DESCRIPTION
**Pull request by pratyushpal**

### CODE REVIEW

**Comment by theRoughCode** [comment]
Build is failing.  Did you `npm install`?  Has to do with bcrypt.  Check out the logs for travisCI below

**Review by theRoughCode — CHANGES_REQUESTED** [review]
Good job, just fix build

**Review by theRoughCode — APPROVED** [review]
Looks good.  Could you post a screenshot?  Thank!

**Comment by pratyushpal** [comment]
screen shot 2018-03-05 at 5 19 20 pm

**Pull request merged**
